// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooIS.Server.Data;

#nullable disable

namespace ZooIS.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230214163129_TBundleTicket")]
    partial class TBundleTicket
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("ZooIS.Shared.Models.RegisteredUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeletionRequested")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PassChangeTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequestPasswordReset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RegisteredUsers");
                });

            modelBuilder.Entity("ZooIS.Shared.Models.TBundle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfUse")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<bool>("PurchaseFinalized")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TBundles");
                });

            modelBuilder.Entity("ZooIS.Shared.Models.TBundleTicket", b =>
                {
                    b.Property<int>("TBundleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicketId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("TBundleId", "TicketId");

                    b.HasIndex("TicketId");

                    b.ToTable("BundleTickets");
                });

            modelBuilder.Entity("ZooIS.Shared.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("ZooIS.Shared.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("ZooIS.Shared.Models.TBundleTicket", b =>
                {
                    b.HasOne("ZooIS.Shared.Models.TBundle", "TBundle")
                        .WithMany("TBundleTickets")
                        .HasForeignKey("TBundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooIS.Shared.Models.Ticket", "Ticket")
                        .WithMany("TBundleTickets")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TBundle");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ZooIS.Shared.Models.UserSettings", b =>
                {
                    b.HasOne("ZooIS.Shared.Models.RegisteredUser", "RegisteredUser")
                        .WithOne("UserSettings")
                        .HasForeignKey("ZooIS.Shared.Models.UserSettings", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegisteredUser");
                });

            modelBuilder.Entity("ZooIS.Shared.Models.RegisteredUser", b =>
                {
                    b.Navigation("UserSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("ZooIS.Shared.Models.TBundle", b =>
                {
                    b.Navigation("TBundleTickets");
                });

            modelBuilder.Entity("ZooIS.Shared.Models.Ticket", b =>
                {
                    b.Navigation("TBundleTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
